routes/web.php
<?php

use App\Http\Livewire\Home;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\BlogController;
use App\Http\Controllers\GitHubController;
use App\Http\Controllers\LoginWithGoogleController;
use App\Http\Controllers\LoginWithFacebookController;
use App\Http\Controllers\UserController;
use Illuminate\Support\Facades\DB;
use App\Http\Requests\PostRequest;
use App\Http\Controllers\ValidationControllers;
use App\Http\Controllers\FlashMessageController;
use App\Http\Livewire\BookingCrud;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', Home::class)->name('/');

Route::resource('users', UserController::class);


Route::get('auth/github', [GitHubController::class, 'gitHubLogin']);
Route::get('auth/github/callback', [GitHubController::class, 'gitHubCallback']);
Route::get('authorized/google', [LoginWithGoogleController::class, 'redirectToGoogle']);
Route::get('authorized/google/callback', [LoginWithGoogleController::class, 'handleGoogleCallback']);
Route::get('/redirect', [LoginWithFacebookController::class, 'redirectFacebook']);
Route::get('/callback', [LoginWithFacebookController::class, 'facebookCallback']);

Route::view('/booking', 'layouts.booking');
Route::view('/profile', 'layouts.profile');

Route::view('/booking-futsal', 'layouts.booking-futsal');
Route::view('/booking-jam-6', 'jambooking.jam6');
Route::view('/booking-jam-7', 'jambooking.jam7');
Route::view('/booking-jam-8', 'jambooking.jam8');
Route::view('/booking-jam-9', 'jambooking.jam9');
Route::view('/booking-jam-10', 'jambooking.jam10');
Route::view('/booking-jam-11', 'jambooking.jam11');
Route::view('/booking-jam-12', 'jambooking.jam12');
Route::view('/booking-jam-13', 'jambooking.jam13');
Route::view('/booking-jam-14', 'jambooking.jam14');
Route::view('/booking-jam-15', 'jambooking.jam15');
Route::view('/booking-jam-16', 'jambooking.jam16');
Route::view('/booking-jam-17', 'jambooking.jam17');
Route::view('/booking-jam-18', 'jambooking.jam18');
Route::view('/booking-jam-19', 'jambooking.jam19');
Route::view('/booking-jam-20', 'jambooking.jam20');
Route::view('/booking-jam-21', 'jambooking.jam21');
Route::view('/booking-jam-22', 'jambooking.jam22');
Route::view('/booking-jam-23', 'jambooking.jam23');

Route::middleware(['auth:sanctum', 'verified'])->get('/dashboard', function () {
    Route::get('dashboard', ' App\Http\Controllers\HomeController@index');
  
    return view('dashboard');
})->name('dashboard');

Route::get('/laporan2', 'App\Http\Controllers\LaporanController@index');
Route::get('/exportlaporan2', 'App\Http\Controllers\LaporanController@export');

Route::get('/laporan', 'App\Http\Controllers\ValidationControllers@index');
Route::get('/exportlaporan', 'App\Http\Controllers\ValidationControllers@export');


Route::resource('/blog', BlogController::class);
Route::resource('/blog-admin', BlogController::class);

Route::resource('valid', ValidationControllers::class);


Route::get('/pesan', 'FlashMessageController@index');
Route::get('/get-pesan', 'FlashMessageController@pesan');

Route::view('data', 'bookingfutsal');
Route::post('data', function (App\Http\Requests\PostRequest $request) {
    $post        = new App\Models\Post();
    $post->nama = $request->nama;
    $post->hp = $request->hp;
    $post->email = $request->email;
    $post->alamat = $request->alamat;
    $post->lapangan = $request->lapangan;
    $post->harga = $request->harga;
    $post->credit = $request->credit;
    $post->save();

    // $post1 = DB::table('post')->get();

    // return back()->with('success', 'Data Added Successfully.');
    if ($post) {
        //redirect dengan pesan sukses
        return back()->with(['success' => 'Data Berhasil Disimpan!']);
    } else {
        //redirect dengan pesan error
        return back()->with(['error' => 'Data Gagal Disimpan!']);
    }
    });

Route::get('/pesan', 'App\Http\Controllers\FlashMessageController@index');
Route::get('/get-pesan', 'App\Http\Controllers\FlashMessageController@pesan');


    

    

app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class AppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        return view('layouts.app');
    }
}

app/View/Components/GuestLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class GuestLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        return view('layouts.guest');
    }
}

resources/views/about.blade.php
<x-app-layout>
    <x-slot name="header">

        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('Dashboard') }}
        </h2>
    </x-slot>
    <br>
{{-- <div class="min-w-screen min-h-screen bg-gray-100 flex items-center justify-center bg-gray-100 font-sans overflow-hidden"> --}}
            <div class="w-full lg:w-5/6">
                <div class="bg-white shadow-md rounded my-6">
                    <table class="min-w-max w-full table-auto">
                        <thead>
                            <tr class="bg-gray-200 text-gray-600 uppercase text-sm leading-normal">
                                <th class="py-3 px-6 text-left">Project</th>
                                <th class="py-3 px-6 text-left">Client</th>
                                <th class="py-3 px-6 text-center">Status</th>
                                <th class="py-3 px-6 text-center">Actions</th>
                            </tr>
                        </thead>

                        <tbody class="text-gray-600 text-sm font-light">
                            <tr class="border-b border-gray-200 hover:bg-gray-100">

                                {{-- Project --}}
                                <td class="py-3 px-6 text-left whitespace-nowrap">
                                    <div class="flex items-center">
                                        <div class="mr-2">
                                            <svg xmlns="http://www.w3.org/2000/svg" x="0px" y="0px"
                                                 width="24" height="24"
                                                 viewBox="0 0 48 48"
                                                 style=" fill:#000000;">
                                                <path fill="#80deea" d="M24,34C11.1,34,1,29.6,1,24c0-5.6,10.1-10,23-10c12.9,0,23,4.4,23,10C47,29.6,36.9,34,24,34z M24,16	c-12.6,0-21,4.1-21,8c0,3.9,8.4,8,21,8s21-4.1,21-8C45,20.1,36.6,16,24,16z"></path><path fill="#80deea" d="M15.1,44.6c-1,0-1.8-0.2-2.6-0.7C7.6,41.1,8.9,30.2,15.3,19l0,0c3-5.2,6.7-9.6,10.3-12.4c3.9-3,7.4-3.9,9.8-2.5	c2.5,1.4,3.4,4.9,2.8,9.8c-0.6,4.6-2.6,10-5.6,15.2c-3,5.2-6.7,9.6-10.3,12.4C19.7,43.5,17.2,44.6,15.1,44.6z M32.9,5.4	c-1.6,0-3.7,0.9-6,2.7c-3.4,2.7-6.9,6.9-9.8,11.9l0,0c-6.3,10.9-6.9,20.3-3.6,22.2c1.7,1,4.5,0.1,7.6-2.3c3.4-2.7,6.9-6.9,9.8-11.9	c2.9-5,4.8-10.1,5.4-14.4c0.5-4-0.1-6.8-1.8-7.8C34,5.6,33.5,5.4,32.9,5.4z"></path><path fill="#80deea" d="M33,44.6c-5,0-12.2-6.1-17.6-15.6C8.9,17.8,7.6,6.9,12.5,4.1l0,0C17.4,1.3,26.2,7.8,32.7,19	c3,5.2,5,10.6,5.6,15.2c0.7,4.9-0.3,8.3-2.8,9.8C34.7,44.4,33.9,44.6,33,44.6z M13.5,5.8c-3.3,1.9-2.7,11.3,3.6,22.2	c6.3,10.9,14.1,16.1,17.4,14.2c1.7-1,2.3-3.8,1.8-7.8c-0.6-4.3-2.5-9.4-5.4-14.4C24.6,9.1,16.8,3.9,13.5,5.8L13.5,5.8z"></path><circle cx="24" cy="24" r="4" fill="#80deea"></circle>
                                            </svg>
                                        </div>
                                        <span class="font-medium">React Project</span>
                                    </div>
                                </td>

                                {{-- Client --}}
                                <td class="py-3 px-6 text-left">
                                    <div class="flex items-center">

                                        <span>Eshal Rosas</span>
                                    </div>
                                </td>

                                {{-- Status --}}
                                <td class="py-3 px-6 text-center">
                                    <span class="bg-purple-200 text-purple-600 py-1 px-3 rounded-full text-xs">Active</span>
                                </td>

                            {{-- Actions --}}
                                <td class="py-3 px-6 text-center">
                                    <div class="flex item-center justify-center">
                                        <div class="w-4 mr-2 transform hover:text-purple-500 hover:scale-110">
                                            <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15 12a3 3 0 11-6 0 3 3 0 016 0z" />
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M2.458 12C3.732 7.943 7.523 5 12 5c4.478 0 8.268 2.943 9.542 7-1.274 4.057-5.064 7-9.542 7-4.477 0-8.268-2.943-9.542-7z" />
                                            </svg>
                                        </div>
                                        <div class="w-4 mr-2 transform hover:text-purple-500 hover:scale-110">
                                            <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15.232 5.232l3.536 3.536m-2.036-5.036a2.5 2.5 0 113.536 3.536L6.5 21.036H3v-3.572L16.732 3.732z" />
                                            </svg>
                                        </div>
                                        <div class="w-4 mr-2 transform hover:text-purple-500 hover:scale-110">
                                            <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M19 7l-.867 12.142A2 2 0 0116.138 21H7.862a2 2 0 01-1.995-1.858L5 7m5 4v6m4-6v6m1-10V4a1 1 0 00-1-1h-4a1 1 0 00-1 1v3M4 7h16" />
                                            </svg>
                                        </div>
                                    </div>
                                </td>
                            </tr>


                        </tbody>
                    </table>
                </div>
            </div>
        </div>
        
</x-app-layout>

resources/views/bookingfutsal.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="h4 font-weight-bold">
            {{ __('Booking') }}
        </h2>
    </x-slot>
<!doctype html>
<html lang="en">
    <head>
        <!-- Required meta tags -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <!-- Bootstrap CSS -->
        {{-- <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous"> --}}
          <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css">
{{-- <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous"> --}}
        <title>Booking Futsal</title>
 
  </head>
    <body>
    <nav style="--bs-breadcrumb-divider: '>';" aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="/">Home</a></li>
    <li class="breadcrumb-item"><a href="/dashboard">Dashboard</a></li>
    <li class="breadcrumb-item active" aria-current="page">Booking</li>
  </ol>
</nav>

        <div class="container my-5">
            <h2 class="fs-4 fw-bold text-center">Booking Futsal</h2>
            <div class="row">
                <div class="col-md-6 offset-md-3">
                    @if (session('success'))
                    <div class="alert alert-success alert-dismissible fade show" role="alert">
                        {{ session('success') }}
                        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                    </div>
                    @endif
                    <form action="data" method="post">
                        @csrf
                        <div class="mb-3">
                            <label for="nama" class="form-label">Nama:</label>
                            <input type="text" name="nama" class="form-control @error('nama') is-invalid @enderror" id="nama" value="{{ old('nama') }} {{ Auth()->User()->name }} ">
                            @error('nama')
                            <div class="invalid-feedback">{{ $message }}</div>
                            @enderror
                        </div>
                        <div class="mb-3">
                            <label for="hp" class="form-label">No.HandPhone:</label>
                            <input type="text" name="hp" class="form-control @error('hp') is-invalid @enderror" id="hp" value="{{ old('hp') }} ">
                            @error('hp')
                            <div class="invalid-feedback">{{ $message }}</div>
                            @enderror
                        </div>
                        
                        <div class="mb-3">
                            <label for="email" class="form-label">Email:</label>
                            <input type="text" name="email" class="form-control @error('email') is-invalid @enderror" id="email" value="{{ old('email') }} {{ Auth()->User()->email }} ">
                            @error('email')
                            <div class="invalid-feedback">{{ $message }}</div>
                            @enderror
                        </div>
                        <div class="mb-3">
                            <label for="alamat" class="form-label">alamat:</label>
                            <input type="text" name="alamat" class="form-control @error('alamat') is-invalid @enderror" id="alamat" value="{{ old('alamat') }} ">
                            @error('alamat')
                            <div class="invalid-feedback">{{ $message }}</div>
                            @enderror
                        </div>

                     <div class="mb-3">
                            <label for="jambooking" class="form-label">Jam Booking:</label>
                           <br>
                            <select class="btn btn-danger" name="jambooking" class="form-control @error('jambooking') is-invalid @enderror" id="jambooking" value="{{ old('jambooking') }}">
                            <option selected>Pilih Jam Booking...</option>
                             <option value="06:00">06:00</option>
                             <option value="07:00">07:00</option>
                             <option value="08:00">08:00</option>
                             <option value="09:00">09:00</option>
                             <option value="10:00">10:00</option>
                             <option value="11:00">11:00</option>
                             <option value="12:00">12:00</option>
                             <option value="13:00">13:00</option>
                             <option value="14:00">14:00</option>
                             <option value="15:00">15:00</option>
                             <option value="16:00">16:00</option>
                             <option value="17:00">17:00</option>
                             <option value="18:00">18:00</option>
                             <option value="19:00">19:00</option>
                             <option value="20:00">20:00</option>
                             <option value="21:00">21:00</option>
                             <option value="22:00">22:00</option>
                             <option value="23:00">23:00</option>
                         </select>
                            @error('jambooking')
                            <div class="invalid-feedback">{{ $message }}</div>
                            @enderror
                        </div>


                        <div class="mb-3">
                            <label for="lapangan" class="form-label">Lapangan:</label>
                           <br>
                            <select class="btn btn-primary" name="lapangan" class="form-control @error('lapangan') is-invalid @enderror" id="lapangan" value="{{ old('lapangan') }}">
                            <option selected>Pilih Lapangan...</option>
                             <option value="Lapangan 1">lapangan1</option>
                                <option value="Lapangan 2">lapangan2</option>
                         </select>
                            @error('lapangan')
                            <div class="invalid-feedback">{{ $message }}</div>
                            @enderror
                        </div>
                        
         

                        
                        <div class="w-full md:w-1/3 px-3 mb-6 md:mb-0">
                        <div class="mb-3">
                            <label for="harga" class="form-label">Harga:</label>
                            <input type="text" name="harga" class="form-control @error('harga') is-invalid @enderror" id="harga"  readonly="disabled" value="{{ old(' harga') }} Rp.45.000 ">
                            @error('harga')
                            <div class="invalid-feedback">{{ $message }}</div>
                            @enderror
                        </div>
                        
                           <div class="mb-3">
                            <label for="credit" class="form-label">Credit:</label>        
                            <br>
                            <select class="btn btn-success" name="credit" class="form-control @error('credit') is-invalid @enderror" id="credit" value="{{ old('credit') }}">
                            <option selected>Pilih Credit...</option>
                             <option value="DANA">DANA</option>
                                <option value="OVO">OVO</option>
                         </select>
                            @error('credit')
                            <div class="invalid-feedback">{{ $message }}</div>
                            @enderror
                        </div>

{{-- 
<div class="form-check">
                        <input  type="radio" name="lapangan" id="lapangan" class="form-check-input @error('lapangan') is-invalid @enderror" id="lapangan" readonly="disabled" value="{{ old('lapangan') }} Lapangan 1">
                        <label class="form-check-label">Lapangan 1</label> 
                         </label>
                        </div>     
                        <div class="form-check">
                        <input  type="radio" name="lapangan" id="lapangan" checked class="form-check-input @error('lapangan') is-invalid @enderror" id="lapangan" readonly="disabled" value="{{ old('lapangan') }} Lapangan 1">
                        <label class="form-check-label" for="credit">Lapangan 2</label>
                        @error('lapangan')
                            <div class="invalid-feedback">{{ $message }}</div>
                            @enderror
                            </div> 
                        </div>
                         <div class="form-check">
                        <input  type="radio" name="credit" id="credit" class="form-check-input @error('credit') is-invalid @enderror" id="credit" readonly="disabled" value="{{ old('credit') }} DANA">
                        <label class="form-check-label">DANA</label> 
                         </label>
                        </div>     
                        <div class="form-check">
                        <input  type="radio" name="credit" id="credit" checked class="form-check-input @error('credit') is-invalid @enderror" id="credit" readonly="disabled" value="{{ old('credit') }} OVO">
                        <label class="form-check-label" for="credit">OVO</label>
                        @error('credit')
                            <div class="invalid-feedback">{{ $message }}</div>
                            @enderror
                            </div> 
                        </div> --}}


                        <button type="submit" class="btn btn-primary btn-lg btn-block mt-4">Kirim</button>
                    </form>
                </div>
            </div>
        </div>
    
    </body>
</html>

</x-app-layout>

resources/views/dashboard.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="h4 font-weight-bold">
            {{ __('Dashboard') }}
        </h2>
    </x-slot>




<!-- JavaScript Bundle with Popper -->
<!-- <script id="Dashboard" for="Dashboard"src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script> -->
   
</x-app-layout>

resources/views/laporan.blade.php
@extends('template')

@section('content')
{{-- <a href="{{ url('exportlaporan') }}" class="btn btn-success mb-4">Export PDF</a> --}}

    <div class="row mt-5 mb-5">
         <a href="{{ url('exportlaporan2') }}" class="btn btn-success mb-4"><i class="fas fa-file-pdf"> Export PDF</i></a>
        <div class="col-lg-12 margin-tb">
        
        </div>
    </div>

    <table class="table table-bordered" width="100%" style="border-collapse: collapse; border: 0px;">
        <h2 style="text-decoration: underline; margin: 10px;">Laporan Booking Futsal</h2>
        <tr>

            <!-- <th width="45px"class="text-center thead-dark" scope="col">No</th> -->
            <th width="45px"class="text-center thead-dark" scope="col">Nama</th>
            <th width="45px"class="text-center thead-dark" scope="col">No.HandPhone</th>
            <th width="45px" class="text-center thead-dark" scope="col">Email</th>
            <th width="45px" class="text-center thead-dark" scope="col">Alamat</th>
            <th width="45px" class="text-center thead-dark" scope="col">Jam Booking</th>
            <th width="45px" class="text-center thead-dark " scope="col">Lapangan</th>
            <th width="45px" class="text-center thead-dark" scope="col">Harga</th>
            <th width="45px" class="text-center thead-dark" scope="col">Credit</th>
            <th width="45px" class="text-center thead-dark" scope="col">Tanggal</th>
 

        </tr>
        @foreach ($valid as $validation)
         @if (Auth()->User()->id == $validation->id_valid || Auth()->User()->role == 'admin')
            
        <tr>

            <!-- <td style="text-align: center;">{{ $i++ }}</td> -->
            <td style="text-align: center;">{{ $validation->nama }}</td>
            <td style="text-align: center;">{{ $validation->hp }}</td>
            <td style="text-align: center;">{{ $validation->email }}</td>
            <td style="text-align: center;">{{ $validation->alamat }}</td>
            <td style="text-align: center;">{{ $validation->jambooking }}</td>
            <td style="text-align: center;">{{ $validation->lapangan }}</td>
            <td style="text-align: center;">{{ $validation->harga }}</td>
            <td style="text-align: center;">{{ $validation->credit }}</td>
            <td style="text-align: center;">{{ $validation->created_at }}</td>

        </tr>
        @endif

        @endforeach
    </table>

@endsection

resources/views/laporan_pdf2.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Laporan</title>
</head>
<body>
        <h2 style="text-decoration: underline; margin: 10px;">Laporan Booking Futsal</h2>
    
<table class="table table-bordered">
        <tr>

            <!-- <th width="70px"class="text-center">No</th> -->
            <th width="70px"class="text-center">Nama</th>
            <th width="70px"class="text-center">No.HandPhone</th>
            <th width="70px" class="text-center">Email</th>
            <th width="70px" class="text-center">Alamat</th>
            <th width="70px" class="text-center">Jam Booking</th>
            <th width="70px" class="text-center">Lapangan</th>
            <th width="70px" class="text-center">Harga</th>
            <th width="70px" class="text-center">Credit</th>
            <th width="70px" class="text-center">Tanggal</th>
 

        </tr>
        @foreach ($valid as $validation)
         @if (Auth()->User()->id == $validation->id_valid || Auth()->User()->role == 'admin')
            
        <tr>

        <!-- <td style="text-align: center;">{{ $validation->id }}</td> -->
            <td style="text-align: center;">{{ $validation->nama }}</td>
            <td style="text-align: center;">{{ $validation->hp }}</td>
            <td style="text-align: center;">{{ $validation->email }}</td>
            <td style="text-align: center;">{{ $validation->alamat }}</td>
            <td style="text-align: center;">{{ $validation->jambooking }}</td>
            <td style="text-align: center;">{{ $validation->lapangan }}</td>
            <td style="text-align: center;">{{ $validation->harga }}</td>
            <td style="text-align: center;">{{ $validation->credit }}</td>
            <td style="text-align: center;">{{ $validation->created_at }}</td>
 
        </tr>
        @endif

        @endforeach
    </table>

</body>
</html>

resources/views/pesan.blade.php
@extends('layouts.master')

@section('content')
 <div class="container">
  <div class="row">
   <div class="col-md-6">
    <a href="{{ url('get-pesan') }}" class="btn btn-danger btn-sm">
        Klik Disini
    </a>
    @if ($message = Session::get('success'))
      <div class="alert alert-success alert-block">
        <button type="button" class="close" data-dismiss="alert">×</button>    
          <strong>{{ $message }}</strong>
      </div>
    @endif

    @if ($message = Session::get('error'))
      <div class="alert alert-danger alert-block">
        <button type="button" class="close" data-dismiss="alert">×</button>    
        <strong>{{ $message }}</strong>
      </div>
    @endif

    @if ($message = Session::get('warning'))
      <div class="alert alert-warning alert-block">
        <button type="button" class="close" data-dismiss="alert">×</button>    
        <strong>{{ $message }}</strong>
    </div>
    @endif

    @if ($message = Session::get('info'))
      <div class="alert alert-info alert-block">
        <button type="button" class="close" data-dismiss="alert">×</button>    
        <strong>{{ $message }}</strong>
      </div>
    @endif

    @if ($errors->any())
      <div class="alert alert-danger">
        <button type="button" class="close" data-dismiss="alert">×</button>    
        Please check the form below for errors
    </div>
    @endif

    <table class="table table-striped">
    <tr>
        <th>#</th>
        <th>Nama</th>
        <th>Perusahaan</th>
    </tr>
    <tr>
        <td>1</td>
        <td>Anugrah Sandi</td>
        <td>Codepolitan</td>
    </tr>
    </table>
  </div>
 </div>
</div>
@endsection

resources/views/policy.blade.php
<x-guest-layout>
    <div class="row justify-content-center pt-4">
        <div class="col-6">
            <div>
                <x-jet-authentication-card-logo />
            </div>

            <div class="card shadow-sm">
                <div class="card-body">
                    {!! $policy !!}
                </div>
            </div>
        </div>
    </div>
    
</x-guest-layout>

resources/views/template.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="h4 font-weight-bold">
            {{ __('') }}
        </h2>
    </x-slot>
<!DOCTYPE html>
<html>
<head>
    <title>Tutorial CRUD Laravel 8 untuk Pemula</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
       <script src="https://kit.fontawesome.com/fbbd9413d8.js" crossorigin="anonymous"></script>
<link rel="stylesheet" href="font-awesome/css/font-awesome.min.css" />


</head>
<body>

<div class="container">
<h2 style="text-decoration: underline;">Booking Futsal</h2>
    @yield('content')
    <br><br>
</div>

</body>
</html>
</x-app-layout>

resources/views/template2.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="h4 font-weight-bold">
            {{ __('Dashboard') }}
        </h2>
    </x-slot>
<!DOCTYPE html>
<html>
<head>
    <title>Tutorial CRUD Laravel 8 untuk Pemula</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
</head>
<body>

<div class="container">
    @yield('content')
    <br><br>
</div>

</body>
</html>
</x-app-layout>

resources/views/terms.blade.php
<x-guest-layout>
    <div class="row justify-content-center pt-4">
        <div class="col-6">
            <div>
                <x-jet-authentication-card-logo />
            </div>

            <div class="card shadow-sm">
                <div class="card-body">
                    {!! $terms !!}
                </div>
            </div>
        </div>
    </div>
    
</x-guest-layout>