routes/web.php
<?php

use App\Http\Livewire\Home;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\BlogController;
use App\Http\Controllers\GitHubController;
use App\Http\Controllers\LoginWithGoogleController;
use App\Http\Controllers\LoginWithFacebookController;
use App\Http\Controllers\UserController;
use Illuminate\Support\Facades\DB;
use App\Http\Requests\PostRequest;
use App\Http\Controllers\ValidationControllers;
use App\Http\Controllers\FlashMessageController;
use App\Http\Livewire\BookingCrud;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', Home::class)->name('/');

Route::resource('users', UserController::class);


Route::get('auth/github', [GitHubController::class, 'gitHubLogin']);
Route::get('auth/github/callback', [GitHubController::class, 'gitHubCallback']);
Route::get('authorized/google', [LoginWithGoogleController::class, 'redirectToGoogle']);
Route::get('authorized/google/callback', [LoginWithGoogleController::class, 'handleGoogleCallback']);
Route::get('/redirect', [LoginWithFacebookController::class, 'redirectFacebook']);
Route::get('/callback', [LoginWithFacebookController::class, 'facebookCallback']);

Route::view('/booking', 'layouts.booking');
Route::view('/profile', 'layouts.profile');

Route::view('/booking-futsal', 'layouts.booking-futsal');
Route::view('/booking-jam-6', 'jambooking.jam6');
Route::view('/booking-jam-7', 'jambooking.jam7');
Route::view('/booking-jam-8', 'jambooking.jam8');
Route::view('/booking-jam-9', 'jambooking.jam9');
Route::view('/booking-jam-10', 'jambooking.jam10');
Route::view('/booking-jam-11', 'jambooking.jam11');
Route::view('/booking-jam-12', 'jambooking.jam12');
Route::view('/booking-jam-13', 'jambooking.jam13');
Route::view('/booking-jam-14', 'jambooking.jam14');
Route::view('/booking-jam-15', 'jambooking.jam15');
Route::view('/booking-jam-16', 'jambooking.jam16');
Route::view('/booking-jam-17', 'jambooking.jam17');
Route::view('/booking-jam-18', 'jambooking.jam18');
Route::view('/booking-jam-19', 'jambooking.jam19');
Route::view('/booking-jam-20', 'jambooking.jam20');
Route::view('/booking-jam-21', 'jambooking.jam21');
Route::view('/booking-jam-22', 'jambooking.jam22');
Route::view('/booking-jam-23', 'jambooking.jam23');

Route::middleware(['auth:sanctum', 'verified'])->get('/dashboard', function () {
    Route::get('dashboard', ' App\Http\Controllers\HomeController@index');
  
    return view('dashboard');
})->name('dashboard');

Route::get('/laporan2', 'App\Http\Controllers\LaporanController@index');
Route::get('/exportlaporan2', 'App\Http\Controllers\LaporanController@export');

Route::get('/laporan', 'App\Http\Controllers\ValidationControllers@index');
Route::get('/exportlaporan', 'App\Http\Controllers\ValidationControllers@export');


Route::resource('/blog', BlogController::class);
Route::resource('/blog-admin', BlogController::class);

Route::resource('valid', ValidationControllers::class);


Route::get('/pesan', 'FlashMessageController@index');
Route::get('/get-pesan', 'FlashMessageController@pesan');

Route::view('data', 'bookingfutsal');
Route::post('data', function (App\Http\Requests\PostRequest $request) {
    $post        = new App\Models\Post();
    $post->nama = $request->nama;
    $post->hp = $request->hp;
    $post->email = $request->email;
    $post->alamat = $request->alamat;
    $post->lapangan = $request->lapangan;
    $post->harga = $request->harga;
    $post->credit = $request->credit;
    $post->save();

    // $post1 = DB::table('post')->get();

    // return back()->with('success', 'Data Added Successfully.');
    if ($post) {
        //redirect dengan pesan sukses
        return back()->with(['success' => 'Data Berhasil Disimpan!']);
    } else {
        //redirect dengan pesan error
        return back()->with(['error' => 'Data Gagal Disimpan!']);
    }
    });

Route::get('/pesan', 'App\Http\Controllers\FlashMessageController@index');
Route::get('/get-pesan', 'App\Http\Controllers\FlashMessageController@pesan');


    

    

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use JoelButcher\Socialstream\HasConnectedAccounts;
use JoelButcher\Socialstream\SetsProfilePhotoFromUrl;
use Laravel\Fortify\TwoFactorAuthenticatable;
use Laravel\Jetstream\HasProfilePhoto;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens;
    use HasFactory;
    use HasProfilePhoto {
        getProfilePhotoUrlAttribute as getPhotoUrl;
    }
    use HasConnectedAccounts;
    use Notifiable;
    use SetsProfilePhotoFromUrl;
    use TwoFactorAuthenticatable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'role', 'hp','alamat', 'email', 'alamat', 'password', 'google_id', 'facebook_id',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
        'two_factor_recovery_codes',
        'two_factor_secret',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    /**
     * The accessors to append to the model's array form.
     *
     * @var array
     */
    protected $appends = [
        'profile_photo_url',
    ];

    /**
     * Get the URL to the user's profile photo.
     *
     * @return string
     */
    public function getProfilePhotoUrlAttribute()
    {
        if (filter_var($this->profile_photo_path, FILTER_VALIDATE_URL)) {
            return $this->profile_photo_path;
        }

        return $this->getPhotoUrl();
    }
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use App\Models\User;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Hash;


class UserController extends Controller
{
    public function index()
    {
        //fungsi eloquent menampilkan data menggunakan pagination
        $users = User::latest()->paginate(5);
        return view('users.index', compact('users'))
            ->with('i', (request()->input('page', 1) - 1) * 5);
    }

    public function create()
    {
        return view('users.create');
    }

    public function store(Request $request)
    {
        //melakukan validasi data
        $request->validate([
            
            'name' => 'required',
            // 'hp' => 'required',
            'email' => 'required',
            // 'alamat' => 'required',
            'password' => 'required|min:5',
        ]);
        $request['password'] = bcrypt($request['password']);
        //fungsi eloquent untuk menambah data
        User::create($request->all());

        //jika data berhasil ditambahkan, akan kembali ke halaman utama
        return redirect()->route('users.index')
            ->with('success', 'User Berhasil Ditambahkan');
    }

    public function show($id)
    {
        //menampilkan detail data dengan menemukan/berdasarkan id user
        $user = User::find($id);
        return view('users.detail', compact('user'));
    }

    public function edit($id)
    {
        //menampilkan detail data dengan menemukan/berdasarkan id user untuk diedit
        $user = User::find($id);
        return view('users.edit', compact('user'));
    }

    public function update(Request $request, $id)
    {
        //melakukan validasi data
        $request->validate([
          
            'name' => 'required',
            // 'hp' => 'required',
            'email' => 'required',
            // 'alamat' => 'required',
            'password' => 'required|min:5',
        ]);
        $request['password'] = bcrypt($request['password']);
        //fungsi eloquent untuk mengupdate data inputan kita
        User::find($id)->update($request->all());

        //jika data berhasil diupdate, akan kembali ke halaman utama
        return redirect()->route('users.index')
            ->with('success', 'User Berhasil Diupdate');
    }

    public function destroy($id)
    {
        //fungsi eloquent untuk menghapus data
        User::find($id)->delete();
        return redirect()->route('users.index')
            ->with('success', 'User Berhasil Dihapus');
    }
}

app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class AppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        return view('layouts.app');
    }
}

resources/views/users/create.blade.php
@extends('users.layout')
  
@section('content')
   
<div class="container mt-5">
   
    <div class="row justify-content-center align-items-center">
        <div class="card" style="width: 24rem;">
            <div class="card-header">
            Tambah User
            </div>
            <div class="card-body">
                @if ($errors->any())
                <div class="alert alert-danger">
                    <strong>Whoops!</strong> There were some problems with your input.<br><br>
                    <ul>
                        @foreach ($errors->all() as $error)
                            <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                </div>
            @endif
            <form method="post" action="{{ route('users.store') }}" id="myForm">
            @csrf
            {{-- <div class="form-group">
                    <label for="role">UserID</label>                    
                    <input type="text" name="role" class="form-control" id="role" aria-describedby="role" >                
                </div>     --}}

                  <div class="mb-3">
                            <label for="role" class="form-label">UserID</label>        
                            <br>
                            <select class="btn btn-success" name="role" class="form-control @error('role') is-invalid @enderror" id="role" value="{{ old('role') }}">
                            <option aria-readonly="disabled" selected>UserID...</option>
                             <option value="admin">Admin</option>
                                <option value="0">User</option>
                         </select>
                            @error('role')
                            <div class="invalid-feedback">{{ $message }}</div>
                            @enderror
                        </div>
            
                <div class="form-group">
                    <label for="name">Name</label>                    
                    <input type="text" name="name" class="form-control" id="name" aria-describedby="name" >                
                </div>
                {{-- <div class="form-group">
                    <label for="hp">No.HandPhone</label>                    
                    <input type="text" name="hp" class="form-control" id="hp" aria-describedby="hp" >                
                </div> --}}
                <div class="form-group">
                    <label for="email">Email</label>                    
                    <input type="email" name="email" class="form-control" id="email" aria-describedby="email" >                
                </div>
                 {{-- <div class="form-group">
                    <label for="alamat">Alamat</label>                    
                    <input type="text" name="alamat" class="form-control" id="alamat" aria-describedby="alamat" >                
                </div> --}}
                        <div class="mt-4">
                <x-jet-label for="password" value="{{ __('Password') }}" />
                <x-jet-input id="password" class="block mt-1 w-full" type="password" name="password" required autocomplete="new-password" />
            </div>
           <br>
            <button type="submit" class="btn btn-primary">Submit</button>
            </form>
            </div>
        </div>
    </div>
    </div>
@endsection

resources/views/users/detail.blade.php
@extends('users.layout')
  
@section('content')

<div class="container mt-5">
    <div class="row justify-content-center align-items-center">
        <div class="card" style="width: 24rem;">
            <div class="card-header">
            Detail User
            </div>
            <div class="card-body">
                <ul class="list-group list-group-flush">
                    <li class="list-group-item"><b>UserID: </b>{{$user->role}}</li>
                    <li class="list-group-item"><b>Name: </b>{{$user->name}}</li>
                    {{-- <li class="list-group-item"><b>No.HandPhone: </b>{{$user->hp}}</li> --}}
                    <li class="list-group-item"><b>Email: </b>{{$user->email}}</li>
                    {{-- <li class="list-group-item"><b>Alamat: </b>{{$user->alamat}}</li> --}}
                </ul>
            </div>
            <a class="btn btn-success mt-3" href="{{ route('users.index') }}">Kembali</a>

        </div>
    </div>
</div>
@endsection

resources/views/users/edit.blade.php
@extends('users.layout')
  
@section('content')
   
<div class="container mt-5">
   
    <div class="row justify-content-center align-items-center">
        <div class="card" style="width: 24rem;">
            <div class="card-header">
            Edit User
            </div>
            <div class="card-body">
                @if ($errors->any())
                <div class="alert alert-danger">
                    <strong>Whoops!</strong> There were some problems with your input.<br><br>
                    <ul>
                        @foreach ($errors->all() as $error)
                            <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                </div>
            @endif
            <form method="post" action="{{ route('users.update', $user->id) }}" id="myForm">
            @csrf
            @method('PUT')
              <div class="mb-3">
                            <label for="role" class="form-label">UserID</label>        
                            <br>
                            <select class="btn btn-success" name="role" class="form-control @error('role') is-invalid @enderror" id="role">
                            <option aria-readonly="disabled" selected for="role" name="role" id="role">UserID...</option>
                             <option value="admin">Admin</option>
                                <option value="0">User</option>
                         </select>
                            @error('role')
                            <div class="invalid-feedback">{{ $message }}</div>
                            @enderror
                        </div>

                <div class="form-group">
                    <label for="name">Name</label>                    
                    <input type="text" name="name" class="form-control" id="name" value="{{ $user->name }}" aria-describedby="name" >                
                </div>
                 {{-- <div class="form-group">
                    <label for="hp">No.Handphone</label>                    
                    <input type="text" name="hp" class="form-control" id="hp" value="{{ $user->hp }}" aria-describedby="hp" >                
                </div> --}}
                <div class="form-group">
                    <label for="email">Email</label>                    
                    <input type="text" name="email" class="form-control" id="email" value="{{ $user->email }}" aria-describedby="email" >                
                </div>
                {{-- <div class="form-group">
                    <label for="alamat">Alamat</label>                    
                    <input type="text" name="alamat" class="form-control" id="alamat" value="{{ $user->alamat }}" aria-describedby="alamat" >                
                </div> --}}
                <div class="form-group">
                    <label for="writer">Password</label>                    
                    <input type="password" name="password" class="form-control" id="password" value="{{ $user->password }}" aria-describedby="password" >                
                </div>
            <button type="submit" class="btn btn-primary">Submit</button>
            </form>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/users/index.blade.php
@extends('users.layout')
 
@section('content')
    <div class="row">
        <div class="col-lg-12 margin-tb">
           
            <div class="float-right my-2">
                <a class="btn btn-success" href="{{ route('users.create') }}"> Create New User</a>
            </div>
        </div>
    </div>
   
    @if ($message = Session::get('success'))
        <div class="alert alert-success">
            <p>{{ $message }}</p>
        </div>
    @endif
   
    <table class="table table-bordered">
        <tr>
            <th>No</th>
            <th>UserID</th>
            <th>Name</th>
            {{-- <th>No.HandPhone</th> --}}
            <th>Email</th>
            {{-- <th>Alamat</th> --}}
            <th width="280px">Action</th>
        </tr>
        @foreach ($users as $user)
        <tr>
            <td>{{ ++$i }}</td>
            <td>{{ $user->role }}</td>
            <td>{{ $user->name }}</td>
            {{-- <td>{{ $user->hp }}</td> --}}
            <td>{{ $user->email }}</td>
            {{-- <td>{{ $user->alamat }}</td> --}}
            <td>
                <form action="{{ route('users.destroy',$user->id) }}" method="POST">
   
                    <a class="btn btn-info" href="{{ route('users.show',$user->id) }}">Show</a>
    
                    <a class="btn btn-primary" href="{{ route('users.edit',$user->id) }}">Edit</a>
   
                    @csrf
                    @method('DELETE')
      
                    <button type="submit" class="btn btn-danger">Delete</button>
                </form>
            </td>
        </tr>
        @endforeach
    </table>
    <div class="text-center">
        {!! $users->links() !!}
    </div>
      
@endsection

resources/views/users/layout.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="h4 font-weight-bold">
            {{ __('Tambah User') }}
        </h2>
    </x-slot>
<!DOCTYPE html>
<html>
    <head>
        <title>Tambah User</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
    </head>
    <body>
            <nav style="--bs-breadcrumb-divider: '>';" aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="/">Home</a></li>
    <li class="breadcrumb-item"><a href="/dashboard">Dashboard</a></li>
    <li class="breadcrumb-item active" aria-current="page">Tambah User</li>
  </ol>
</nav>
        <div class="container">
            @yield('content')
        </div>
    </body>
</html>
</x-app-layout>