routes/web.php
<?php

use App\Http\Livewire\Home;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\BlogController;
use App\Http\Controllers\GitHubController;
use App\Http\Controllers\LoginWithGoogleController;
use App\Http\Controllers\LoginWithFacebookController;
use App\Http\Controllers\UserController;
use Illuminate\Support\Facades\DB;
use App\Http\Requests\PostRequest;
use App\Http\Controllers\ValidationControllers;
use App\Http\Controllers\FlashMessageController;
use App\Http\Livewire\BookingCrud;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', Home::class)->name('/');

Route::resource('users', UserController::class);


Route::get('auth/github', [GitHubController::class, 'gitHubLogin']);
Route::get('auth/github/callback', [GitHubController::class, 'gitHubCallback']);
Route::get('authorized/google', [LoginWithGoogleController::class, 'redirectToGoogle']);
Route::get('authorized/google/callback', [LoginWithGoogleController::class, 'handleGoogleCallback']);
Route::get('/redirect', [LoginWithFacebookController::class, 'redirectFacebook']);
Route::get('/callback', [LoginWithFacebookController::class, 'facebookCallback']);

Route::view('/booking', 'layouts.booking');
Route::view('/profile', 'layouts.profile');

Route::view('/booking-futsal', 'layouts.booking-futsal');
Route::view('/booking-jam-6', 'jambooking.jam6');
Route::view('/booking-jam-7', 'jambooking.jam7');
Route::view('/booking-jam-8', 'jambooking.jam8');
Route::view('/booking-jam-9', 'jambooking.jam9');
Route::view('/booking-jam-10', 'jambooking.jam10');
Route::view('/booking-jam-11', 'jambooking.jam11');
Route::view('/booking-jam-12', 'jambooking.jam12');
Route::view('/booking-jam-13', 'jambooking.jam13');
Route::view('/booking-jam-14', 'jambooking.jam14');
Route::view('/booking-jam-15', 'jambooking.jam15');
Route::view('/booking-jam-16', 'jambooking.jam16');
Route::view('/booking-jam-17', 'jambooking.jam17');
Route::view('/booking-jam-18', 'jambooking.jam18');
Route::view('/booking-jam-19', 'jambooking.jam19');
Route::view('/booking-jam-20', 'jambooking.jam20');
Route::view('/booking-jam-21', 'jambooking.jam21');
Route::view('/booking-jam-22', 'jambooking.jam22');
Route::view('/booking-jam-23', 'jambooking.jam23');

Route::middleware(['auth:sanctum', 'verified'])->get('/dashboard', function () {
    Route::get('dashboard', ' App\Http\Controllers\HomeController@index');
  
    return view('dashboard');
})->name('dashboard');

Route::get('/laporan2', 'App\Http\Controllers\LaporanController@index');
Route::get('/exportlaporan2', 'App\Http\Controllers\LaporanController@export');

Route::get('/laporan', 'App\Http\Controllers\ValidationControllers@index');
Route::get('/exportlaporan', 'App\Http\Controllers\ValidationControllers@export');


Route::resource('/blog', BlogController::class);
Route::resource('/blog-admin', BlogController::class);

Route::resource('valid', ValidationControllers::class);


Route::get('/pesan', 'FlashMessageController@index');
Route::get('/get-pesan', 'FlashMessageController@pesan');

Route::view('data', 'bookingfutsal');
Route::post('data', function (App\Http\Requests\PostRequest $request) {
    $post        = new App\Models\Post();
    $post->nama = $request->nama;
    $post->hp = $request->hp;
    $post->email = $request->email;
    $post->alamat = $request->alamat;
    $post->lapangan = $request->lapangan;
    $post->harga = $request->harga;
    $post->credit = $request->credit;
    $post->save();

    // $post1 = DB::table('post')->get();

    // return back()->with('success', 'Data Added Successfully.');
    if ($post) {
        //redirect dengan pesan sukses
        return back()->with(['success' => 'Data Berhasil Disimpan!']);
    } else {
        //redirect dengan pesan error
        return back()->with(['error' => 'Data Gagal Disimpan!']);
    }
    });

Route::get('/pesan', 'App\Http\Controllers\FlashMessageController@index');
Route::get('/get-pesan', 'App\Http\Controllers\FlashMessageController@pesan');


    

    

app/Models/Blog.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Blog extends Model
{
    use HasFactory;
    
    protected $fillable = [
        'role','image', 'title','userid'
    ];
    public function user()
    {
        return $this->belongsTo(User::class);
    }
}

app/Http/Controllers/BlogController.php
<?php

namespace App\Http\Controllers;

use App\Models\Blog;
// use App\Blog;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Models\Validation;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Storage;

class BlogController extends Controller
{
    /**
     * index
     *
     * @return void
     */
    public function index()
    {
        $blogs = Blog::latest()->paginate(10);
        $valid = Validation::All();
        // $blogs = Auth::First()->Auth()->User()->role == admin;

        // return view('blog.index', compact('blogs'));
        // return view('blog.index-admin', compact('blogs'));

        if ($blogs == '0') {
            return view('blog.index-admin', compact('blogs','valid'));
        } else {
            return view('blog.index', compact('blogs','valid'));
        }

    }

    public function create()
    {
        return view('blog.create');
    }


    /**
     * store
     *
     * @param  mixed $request
     * @return void
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'image'     => 'required|image|mimes:png,jpg,jpeg',
            'role'     => 'required',
            'title'     => 'required',
            'userid'     => 'required',
            // 'content'   => 'required'
        ]);

        //upload image
        $image = $request->file('image');
        $image->storeAs('public/blogs', $image->hashName());

        $blog = Blog::create([
            'image'     => $image->hashName(),
            'role'     => $request->role,
            'title'     => $request->title,
            'userid'     => $request->userid,
            
            // 'content'   => $request->content
        ]);

        if ($blog) {
            //redirect dengan pesan sukses
            return redirect()->route('blog.index')->with(['success' => 'Data Berhasil Disimpan!']);
            return redirect()->route('blog.index-admin')->with(['success' => 'Data Berhasil Disimpan!']);

        } else {
            //redirect dengan pesan error
            return redirect()->route('blog.index')->with(['error' => 'Data Gagal Disimpan!']);
            return redirect()->route('blog.index-admin')->with(['error' => 'Data Gagal Disimpan!']);

        }
    }

    public function edit(Blog $blog)
    {
        return view('blog.edit', compact('blog'));
    }


    /**
     * update
     *
     * @param  mixed $request
     * @param  mixed $blog
     * @return void
     */
    public function update(Request $request, Blog $blog)
    {
        $this->validate($request, [
            'role'     => 'required',
            'title'     => 'required',
            'userid'     => 'required',
            // 'content'   => 'required'
        ]);

        //get data Blog by ID
        $blog = Blog::findOrFail($blog->id);

        if ($request->file('image') == "") {

            $blog->update([
                'role'     => $request->role,
                'title'     => $request->title,
                'userid'     => $request->userid,
                // 'content'   => $request->content
            ]);
        } else {

            //hapus old image
            Storage::disk('local')->delete('public/blogs/' . $blog->image);

            //upload new image
            $image = $request->file('image');
            $image->storeAs('public/blogs', $image->hashName());

            $blog->update([
                'image'     => $image->hashName(),
                'role'     => $request->role,
                'title'     => $request->title,
                'userid'     => $request->userid,
                // 'content'   => $request->content
            ]);
        }

        if ($blog) {
            //redirect dengan pesan sukses
            return redirect()->route('blog.index')->with(['success' => 'Data Berhasil Diupdate!']);
            return redirect()->route('blog.index-admin')->with(['success' => 'Data Berhasil Diupdate!']);
            
        } else {
            //redirect dengan pesan error
            return redirect()->route('blog.index')->with(['error' => 'Data Gagal Diupdate!']);
            return redirect()->route('blog.index-admin')->with(['error' => 'Data Gagal Diupdate!']);
        }
    }
    public function destroy($id)
    {
        $blog = Blog::findOrFail($id);
        Storage::disk('local')->delete('public/blogs/' . $blog->image);
        $blog->delete();

        if ($blog) {
            //redirect dengan pesan sukses
            return redirect()->route('blog.index')->with(['success' => 'Data Berhasil Dihapus!']);
            return redirect()->route('blog.index-admin')->with(['success' => 'Data Berhasil Dihapus!']);
        } else {
            //redirect dengan pesan error
            return redirect()->route('blog.index')->with(['error' => 'Data Gagal Dihapus!']);
            return redirect()->route('blog.index-admin')->with(['error' => 'Data Gagal Dihapus!']);
        }
    }
}

app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class AppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        return view('layouts.app');
    }
}

resources/views/blog/create.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="h4 font-weight-bold">
            {{ __('Create Bukti DP :') }}
        </h2>
    </x-slot>

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Tambah Upload Bukti DP</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
</head>
<body style="background: lightgray">

    <div class="container mt-1 mb-5">
        <div class="row">
            <div class="col-md-12">
                <div class="card border-0 shadow rounded">
                    <div class="card-body">
                        <form action="{{ route('blog.store') }}" method="POST" enctype="multipart/form-data">
                        
                            @csrf

                            <div class="form-group">
                                <label class="font-weight-bold">GAMBAR</label>
                                <input type="file" class="form-control @error('image') is-invalid @enderror" name="image">
                            
                                <!-- error message untuk title -->
                                @error('image')
                                    <div class="alert alert-danger mt-2">
                                        {{ $message }}
                                    </div>
                                @enderror
                            </div>

                            <div class="form-group">
                                <label class="font-weight-bold">Nama :</label>
                                <input type="text" class="form-control @error('title') is-invalid @enderror" name="title" value=" {{ Auth()->User()->name }}" placeholder="Masukkan Nama">
                            
                                <!-- error message untuk title -->
                                @error('title')
                                    <div class="alert alert-danger mt-2">
                                        {{ $message }}
                                    </div>
                                @enderror
                            </div>

                            <div class="form-group">
                                <label class="font-weight-bold">userid :</label>
                                <input type="text" class="form-control @error('userid') is-invalid @enderror" name="userid" readonly="disabled" value=" {{ Auth()->User()->id }}" placeholder="Masukkan userid">
                            
                                <!-- error message untuk title -->
                                @error('userid')
                                    <div class="alert alert-danger mt-2">
                                        {{ $message }}
                                    </div>
                                @enderror
                            </div>

                               <div class="form-group">
                                {{-- <label class="font-weight-bold">Role :</label> --}}
                                <input type="hidden" class="form-control @error('role') is-invalid @enderror" name="role" readonly="disabled" value=" {{ Auth()->User()->role }}" placeholder="Masukkan role">
                            
                                <!-- error message untuk title -->
                                @error('role')
                                    <div class="alert alert-danger mt-2">
                                        {{ $message }}
                                    </div>
                                @enderror
                            </div>

                            {{-- <div class="form-group">
                                <label class="font-weight-bold">KONTEN</label>
                                <textarea class="form-control @error('content') is-invalid @enderror" name="content" rows="5" placeholder="Masukkan Konten Blog">{{ old('content') }}</textarea>
                            
                                <!-- error message untuk content -->
                                @error('content')
                                    <div class="alert alert-danger mt-2">
                                        {{ $message }}
                                    </div>
                                @enderror
                            </div> --}}

                            <button type="submit" class="btn btn-md btn-primary">SIMPAN</button>
                            <button type="reset" class="btn btn-md btn-warning">RESET</button>

                        </form> 
                    </div>
                </div>
            </div>
        </div>
    </div>
    
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
<script src="https://cdn.ckeditor.com/4.13.1/standard/ckeditor.js"></script>
<script>
    CKEDITOR.replace( 'content' );
</script>
</body>
</html>

</x-app-layout>

resources/views/blog/edit.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="h4 font-weight-bold">
            {{ __('Edit Upload Bukti DP :') }}
        </h2>
    </x-slot>

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Edit Data Blog - SantriKoding.com</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
</head>
<body style="background: lightgray">

    <div class="container mt-5 mb-5">
        <div class="row">
            <div class="col-md-12">
                <div class="card border-0 shadow rounded">
                    <div class="card-body">
                        <form action="{{ route('blog.update', $blog->id) }}" method="POST" enctype="multipart/form-data">
                            @csrf
                            @method('PUT')

                            <div class="form-group">
                                <label class="font-weight-bold">GAMBAR</label>
                                <input type="file" class="form-control" name="image">
                            </div>

                            <div class="form-group">
                                <label class="font-weight-bold">Nama</label>
                                <input type="text" class="form-control @error('title') is-invalid @enderror" name="title" value="{{ old('title', $blog->title) }}" placeholder="Masukkan nama">
                            
                                <!-- error message untuk title -->
                                @error('title')
                                    <div class="alert alert-danger mt-2">
                                        {{ $message }}
                                    </div>
                                @enderror
                            </div>
                            
                            <div class="form-group">
                                <label class="font-weight-bold">UserID</label>
                                <input type="text" class="form-control @error('userid') is-invalid @enderror" name="userid" value="{{ old('userid', $blog->userid) }}" placeholder="Masukkan userid">
                            
                                <!-- error message untuk title -->
                                @error('userid')
                                    <div class="alert alert-danger mt-2">
                                        {{ $message }}
                                    </div>
                                @enderror
                            </div>

                            <div class="form-group">
                                {{-- <label class="font-weight-bold">Role</label> --}}
                                <input type="hidden" class="form-control @error('role') is-invalid @enderror" name="role" value="{{ old('role', $blog->role) }}" placeholder="Masukkan role">
                            
                                <!-- error message untuk title -->
                                @error('role')
                                    <div class="alert alert-danger mt-2">
                                        {{ $message }}
                                    </div>
                                @enderror
                            </div>

                            {{-- <div class="form-group">
                                <label class="font-weight-bold">KONTEN</label>
                                <textarea class="form-control @error('content') is-invalid @enderror" name="content" rows="5" placeholder="Masukkan Konten Blog">{{ old('content', $blog->content) }}</textarea>
                            
                                <!-- error message untuk content -->
                                @error('content')
                                    <div class="alert alert-danger mt-2">
                                        {{ $message }}
                                    </div>
                                @enderror
                            </div> --}}

                            <button type="submit" class="btn btn-md btn-primary">UPDATE</button>
                            <button type="reset" class="btn btn-md btn-warning">RESET</button>

                        </form> 
                    </div>
                </div>
            </div>
        </div>
    </div>
    
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
<script src="https://cdn.ckeditor.com/4.13.1/standard/ckeditor.js"></script>
<script>
    CKEDITOR.replace( 'content' );
</script>
</body>
</html>

</x-app-layout>

resources/views/blog/index-admin.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="h4 font-weight-bold">
            {{ __('Upload Bukti DP :') }}
        </h2>
    </x-slot>

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Data Blogs - SantriKoding.com</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css">
</head>

<body style="background: lightgray">
    
 <b><p style="font-style: italic;">Segera Chat Pemilik! apabila sudah mengirim Bukti DP.</p></b>
 <button type="submit" class="btn btn-sm btn-success"> <i class="fab fa-whatsapp fa-2x"></i>
        <a href="https://wa.me/6285314005779?text=
  *Hallo Admin!* Nama saya *{{ Auth()->User()->name }}* ingin bertanya.
  " style="color: #ffff; text-decoration: none;">Chat Via WhatsApp</a>

</button>

    <div class="container mt-5">
        <div class="row">
            <div class="col-md-12">
                <div class="card border-0 shadow rounded">
                    <div class="card-body">
                        <a href="{{ route('blog.create') }}" class="btn btn-md btn-success mb-3">Upload</a>
                        
             
                        <table class="table table-bordered">
                            <thead>
                              <tr>
                                <th scope="col">Bukti DP</th>
                                <th scope="col">Nama</th>
                                <th scope="col">UserID</th>
                                <th scope="col">Role</th>
                                <th scope="col">Tanggal</th>
                                <th scope="col">Action</th>
                                
                                
                            </tr>
                            </thead>
                            <tbody>
                              @forelse ($blogs as $blog)
                                    @if (Auth()->User()->id == $blog->userid || Auth()->User()->role == 'admin')        

                                <tr>
                                    <td class="text-center">
                                        <img src="{{ Storage::url('public/blogs/').$blog->image }}" class="rounded" style="width: 150px">
                                    </td>
                                    <td>{{ $blog->title }}</td>
                                    <td>{{ $blog->userid }}</td>
                                    <td>{{ $blog->role }}</td>
                                    <td>{{ $blog->created_at }}</td>
                                  

                                    <td class="text-center">
                                        <form onsubmit="return confirm('Apakah Anda Yakin ?');" action="{{ route('blog.destroy', $blog->id) }}" method="POST">
                                            <a href="{{ route('blog.edit', $blog->id) }}" class="btn btn-sm btn-primary">EDIT</a>
                                            @csrf
                                            @method('DELETE')
                                            <button type="submit" class="btn btn-sm btn-danger">HAPUS</button>
                                        </form>
                                    </td>
                                </tr>
                         
                              @empty
                                  <div class="alert alert-danger">
                                      Data Blog belum Tersedia.
                                  </div>
                              @endforelse
                            </tbody>
                          </table>  
                          {{ $blogs->links() }}
                    </div>
                </div>
            </div>
        </div>
    </div>
    
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>

    <script>
        //message with toastr
        @if(session()->has('success'))
        
            toastr.success('{{ session('success') }}', 'BERHASIL!'); 

        @elseif(session()->has('error'))

            toastr.error('{{ session('error') }}', 'GAGAL!'); 
            
        @endif
    </script>

</body>
</html>

</x-app-layout>

resources/views/blog/index.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="h4 font-weight-bold">
            {{ __('Upload Bukti DP :') }}
        </h2>
    </x-slot>

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Data Upload</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css">
</head>

<body style="background: lightgray">
    <nav style="--bs-breadcrumb-divider: '>';" aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="/">Home</a></li>
    <li class="breadcrumb-item"><a href="/dashboard">Dashboard</a></li>
    <li class="breadcrumb-item active" aria-current="page">Upload Bukti DP</li>
  </ol>
</nav>

  <b><p style="font-style: italic;">Segera Chat Pemilik! apabila sudah mengirim Bukti DP.</p></b>
 <button type="submit" class="btn btn-sm btn-success"> <i class="fab fa-whatsapp fa-2x"></i>
        <a href="https://wa.me/6285314005779?text=
  *Hallo Admin!* Nama saya *{{ Auth()->User()->name }}* ingin bertanya.
  " style="color: #ffff; text-decoration: none;">Chat Via WhatsApp</a>
</button>
<br><br>
         <button type="button" style="font-size: 25px;" class="btn btn-primary">Dana: <span class="badge" style="font-size: 20px;">085123456789</span></button>
         <button type="button" style="font-size: 25px;" class="btn btn-primary">Ovo: <span class="badge" style="font-size: 20px;">01234567890</span></button>
  
    <div class="container mt-5">
        <div class="row">
            <div class="col-md-12">
                <div class="card border-0 shadow rounded">
                    <div class="card-body">
                        <a href="{{ route('blog.create') }}" class="btn btn-md btn-success mb-3">Upload</a>
                        
             
                        <table class="table table-bordered">
                            <thead>
                              <tr>
                                <th scope="col">Bukti DP</th>
                                <th scope="col">Nama</th>
                                <th scope="col">UserID</th>
                                {{-- <th scope="col">Role</th> --}}
                                <th scope="col">Tanggal</th>
                                <th scope="col">Action</th>
                                
                                
                            </tr>
                            </thead>
                            <tbody>
                              @forelse ($blogs as $blog)
                                    @if (Auth()->User()->id == $blog->userid || Auth()->User()->role == 'admin')
                                    <!-- <br><br><a href="/valid/create"><img src="{{ Storage::url('public/blogs/').$blog->image }}" class="rounded" style="width: 150px">
                                    </a><br><br> -->
                                    <tr>
                                    <td class="text-center">
                                        <img src="{{ Storage::url('public/blogs/').$blog->image }}" class="rounded" style="width: 150px">
                                    </td>
                                    <td>{{ $blog->title }}</td>
                                    <td>{{ $blog->userid }}</td>
                                    {{-- <td>{{ $blog->role }}</td> --}}
                                    <td>{{ $blog->created_at }}</td>
                                  

                                    <td class="text-center">
                                        <form onsubmit="return confirm('Apakah Anda Yakin ?');" action="{{ route('blog.destroy', $blog->id) }}" method="POST">
                                            <a href="{{ route('blog.edit', $blog->id) }}" class="btn btn-sm btn-primary">EDIT</a>
                                            @csrf
                                            @method('DELETE')
                                            <button type="submit" class="btn btn-sm btn-danger">HAPUS</button>
                                        </form>
                                    </td>
                                </tr>
                                       @endif
                              @empty
                                  <div class="alert alert-danger">
                                      Data Blog belum Tersedia.
                                  </div>
                              @endforelse
                            </tbody>
                          </table>  
                          {{ $blogs->links() }}
                    </div>
                </div>
            </div>
        </div>
    </div>
    
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>

    <script>
        //message with toastr
        @if(session()->has('success'))
        
            toastr.success('{{ session('success') }}', 'BERHASIL!'); 

        @elseif(session()->has('error'))

            toastr.error('{{ session('error') }}', 'GAGAL!'); 
            
        @endif
    </script>

</body>
</html>

</x-app-layout>