routes/web.php
<?php

use App\Http\Livewire\Home;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\BlogController;
use App\Http\Controllers\GitHubController;
use App\Http\Controllers\LoginWithGoogleController;
use App\Http\Controllers\LoginWithFacebookController;
use App\Http\Controllers\UserController;
use Illuminate\Support\Facades\DB;
use App\Http\Requests\PostRequest;
use App\Http\Controllers\ValidationControllers;
use App\Http\Controllers\FlashMessageController;
use App\Http\Livewire\BookingCrud;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', Home::class)->name('/');

Route::resource('users', UserController::class);


Route::get('auth/github', [GitHubController::class, 'gitHubLogin']);
Route::get('auth/github/callback', [GitHubController::class, 'gitHubCallback']);
Route::get('authorized/google', [LoginWithGoogleController::class, 'redirectToGoogle']);
Route::get('authorized/google/callback', [LoginWithGoogleController::class, 'handleGoogleCallback']);
Route::get('/redirect', [LoginWithFacebookController::class, 'redirectFacebook']);
Route::get('/callback', [LoginWithFacebookController::class, 'facebookCallback']);

Route::view('/booking', 'layouts.booking');
Route::view('/profile', 'layouts.profile');

Route::view('/booking-futsal', 'layouts.booking-futsal');
Route::view('/booking-jam-6', 'jambooking.jam6');
Route::view('/booking-jam-7', 'jambooking.jam7');
Route::view('/booking-jam-8', 'jambooking.jam8');
Route::view('/booking-jam-9', 'jambooking.jam9');
Route::view('/booking-jam-10', 'jambooking.jam10');
Route::view('/booking-jam-11', 'jambooking.jam11');
Route::view('/booking-jam-12', 'jambooking.jam12');
Route::view('/booking-jam-13', 'jambooking.jam13');
Route::view('/booking-jam-14', 'jambooking.jam14');
Route::view('/booking-jam-15', 'jambooking.jam15');
Route::view('/booking-jam-16', 'jambooking.jam16');
Route::view('/booking-jam-17', 'jambooking.jam17');
Route::view('/booking-jam-18', 'jambooking.jam18');
Route::view('/booking-jam-19', 'jambooking.jam19');
Route::view('/booking-jam-20', 'jambooking.jam20');
Route::view('/booking-jam-21', 'jambooking.jam21');
Route::view('/booking-jam-22', 'jambooking.jam22');
Route::view('/booking-jam-23', 'jambooking.jam23');

Route::middleware(['auth:sanctum', 'verified'])->get('/dashboard', function () {
    Route::get('dashboard', ' App\Http\Controllers\HomeController@index');
  
    return view('dashboard');
})->name('dashboard');

Route::get('/laporan2', 'App\Http\Controllers\LaporanController@index');
Route::get('/exportlaporan2', 'App\Http\Controllers\LaporanController@export');

Route::get('/laporan', 'App\Http\Controllers\ValidationControllers@index');
Route::get('/exportlaporan', 'App\Http\Controllers\ValidationControllers@export');


Route::resource('/blog', BlogController::class);
Route::resource('/blog-admin', BlogController::class);

Route::resource('valid', ValidationControllers::class);


Route::get('/pesan', 'FlashMessageController@index');
Route::get('/get-pesan', 'FlashMessageController@pesan');

Route::view('data', 'bookingfutsal');
Route::post('data', function (App\Http\Requests\PostRequest $request) {
    $post        = new App\Models\Post();
    $post->nama = $request->nama;
    $post->hp = $request->hp;
    $post->email = $request->email;
    $post->alamat = $request->alamat;
    $post->lapangan = $request->lapangan;
    $post->harga = $request->harga;
    $post->credit = $request->credit;
    $post->save();

    // $post1 = DB::table('post')->get();

    // return back()->with('success', 'Data Added Successfully.');
    if ($post) {
        //redirect dengan pesan sukses
        return back()->with(['success' => 'Data Berhasil Disimpan!']);
    } else {
        //redirect dengan pesan error
        return back()->with(['error' => 'Data Gagal Disimpan!']);
    }
    });

Route::get('/pesan', 'App\Http\Controllers\FlashMessageController@index');
Route::get('/get-pesan', 'App\Http\Controllers\FlashMessageController@pesan');


    

    

resources/views/valid/create.blade.php
@extends('template')

@section('content')
<div class="row mt-5 mb-5">
    <div class="col-lg-12 margin-tb">
        <div class="float-left">
            <h2>Create New Data</h2>
        </div>
        <div class="float-right">
            <a class="btn btn-secondary" href="{{ route('valid.index') }}"> Kembali</a>
        </div>
    </div>
</div>

@if ($errors->any())
    <div class="alert alert-danger">
        <strong>Whoops!</strong> Input gagal.<br><br>
        <ul>
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
@endif

<form action="{{ route('valid.store') }}" method="POST">
    @csrf
@section('content')
<div class="row mt-5 mb-5">
    <div class="col-lg-12 margin-tb">
        <div class="float-left">
            <h2>Create New Data</h2>
        </div>
        <div class="float-right">
            <a class="btn btn-secondary" href="{{ route('valid.index') }}"> Kembali</a>
        </div>
    </div>
</div>

@if ($errors->any())
    <div class="alert alert-danger">
        <strong>Whoops!</strong> Input gagal.<br><br>
        <ul>
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
@endif

<form action="{{ route('valid.store') }}" method="POST">
    @csrf


      <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                {{-- <strong>Role:</strong> --}}
                <input type="hidden" name="role" class="form-control" readonly="disabled" placeholder="role" value="{{ Auth()->User()->role }}">
            </div>
        </div>

        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                {{-- <strong>ID_Valid:</strong> --}}
                <input type="hidden" name="id_valid" class="form-control" readonly="disabled" placeholder="ID_Valid" value="{{ Auth()->User()->id }}">
            </div>
        </div>

        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Status_Booking:</strong>
                <input type="text" name="status_booking" class="form-control" readonly="disabled" placeholder="status_booking" value="Sudah Booking">
            </div>
        </div>

        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Nama:</strong>
                <input type="text" name="nama" class="form-control" placeholder="NAMA" value="{{ Auth()->User()->name }}">
            </div>
        </div>

         <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>No.HandPhone:</strong>
                <input type="text" name="hp" class="form-control" placeholder="No.HP" value="">
            </div>
        </div>
        
         <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Email:</strong>
                <input type="text" name="email" class="form-control" placeholder="Email" value="{{ Auth()->User()->email }}">
            </div>
        </div>

         <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Alamat:</strong>
                 <textarea class="form-control" name="alamat" rows="5" placeholder="Alamat"></textarea>
            </div>
        </div>
        
     

  
          
      
         <div class="mb-3">
                            <label for="jambooking" class="form-label">Jam Booking:</label>
                           <br>
                            <select class="btn btn-danger" name="jambooking" class="form-control @error('jambooking') is-invalid @enderror" id="jambooking" value="{{ old('jambooking') }}">
                            <option selected>Pilih Jam Booking...</option>
                        
                       
                            @if ($valid->jambooking == "06.00" || $valid->status_booking == 1)
                                
                                @elseif ($valid->jambooking == "06.00" || $valid->status_booking == 0)
                                    <option value="06:00">06:00</option>
                                @else
                                <option value="06:00">sudah dibooking</option>
                            
                           @endif
                             <option value="07:00">07:00</option>
                             <option value="08:00">08:00</option>
                             <option value="09:00">09:00</option>
                             <option value="10:00">10:00</option>
                             <option value="11:00">11:00</option>
                             <option value="12:00">12:00</option>
                             <option value="13:00">13:00</option>
                             <option value="14:00">14:00</option>
                             <option value="15:00">15:00</option>
                             <option value="16:00">16:00</option>
                             <option value="17:00">17:00</option>
                             <option value="18:00">18:00</option>
                             <option value="19:00">19:00</option>
                             <option value="20:00">20:00</option>
                             <option value="21:00">21:00</option>
                             <option value="22:00">22:00</option>
                             <option value="23:00">23:00</option>
                    
                         </select>
                            @error('jambooking')
                            <div class="invalid-feedback">{{ $message }}</div>
                            @enderror
                        </div>
        <div div class=" ml-3 mb-3">
                            <label for="lapangan" class="form-label">Lapangan:</label>
                           <br>
                            <select class="btn btn-primary" name="lapangan" class="form-control @error('lapangan') is-invalid @enderror" id="lapangan" value="{{ old('lapangan') }}">
                            <option selected>Pilih Lapangan...</option>
                             <option value="Lapangan 1">lapangan1</option>
                                <option value="Lapangan 2">lapangan2</option>
                         </select>
                            @error('lapangan')
                            <div class="invalid-feedback">{{ $message }}</div>
                            @enderror
                        </div>

         <div class="mb-3">
                            <label for="harga" class="form-label">Harga:</label>        
                            <br>
                            <select class="btn btn-success" name="harga" class="form-control @error('harga') is-invalid @enderror" id="harga" value="{{ old('harga') }}">
                            <option selected>Pilih Credit...</option>
                             <option value="10.000">Rp.10.000</option>
                                <option value="20.000">Rp.20.000</option>
                         </select>
                            @error('harga')
                            <div class="invalid-feedback">{{ $message }}</div>
                            @enderror
                        </div>


                     <div class="mb-3">
                            <label for="credit" class="form-label">Credit:</label>        
                            <br>
                            <select class="btn btn-success" name="credit" class="form-control @error('credit') is-invalid @enderror" id="credit" value="{{ old('credit') }}">
                            <option selected>Pilih Credit...</option>
                             <option value="DANA">DANA</option>
                                <option value="OVO">OVO</option>
                         </select>
                            @error('credit')
                            <div class="invalid-feedback">{{ $message }}</div>
                            @enderror
                        </div>
                
                       <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                {{-- <strong>Status:</strong> --}}
                <input type="hidden" name="status" class="form-control" placeholder="Status" value='Belum Lunas' readonly="disabled">
            </div>
        </div>

        <div class="col-xs-12 col-sm-12 col-md-12 text-center">
            <button type="submit" class="btn btn-primary">Submit</button>
        </div>
    </div>

</form>
@endsection.store

 
@endsection

resources/views/valid/edit.blade.php
@extends('template')

@section('content')
    <div class="row mt-5 mb-5">
        <div class="col-lg-12 margin-tb">
            <div class="float-left">
                <h2>Edit Data</h2>
            </div>
            <div class="float-right">
                <a class="btn btn-secondary" href="{{ route('valid.index') }}"> Back</a>
            </div>
        </div>
    </div>

    @if ($errors->any())
        <div class="alert alert-danger">
            <strong>Whoops!</strong> There were some problems with your input.<br><br>
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif

    <form action="{{ route('valid.update',$valid->id) }}" method="POST">
        @csrf
        @method('PUT')

        <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                {{-- <strong>Role:</strong> --}}
                <input type="hidden" name="role" class="form-control" readonly="disabled" placeholder="Role" value="{{ $valid->role }}">
            </div>
        </div>

        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                {{-- <strong>Id_Valid:</strong> --}}
                <input type="hidden" name="id_valid" class="form-control" readonly="disabled" placeholder="Id_valid" value="{{ $valid->id_valid }}">
            </div>
        </div>
                     

        <div div class=" ml-3 mb-3">
              <label for="status" class="form-label">Status Booking:</label>
                <br>
                   <select class="btn btn-primary" name="status_booking" class="form-control @error('status_booking') is-invalid @enderror" id="status_booking" value="{{ $valid->status_booking }}">
                     <option selected value="Belum Booking">Belum Booking</option>
                          <option value="Sudah Booking">Sudah Booking</option>
                </select>
            </div>

        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Nama:</strong>
                <input type="text" name="nama" class="form-control" placeholder="Nama" value="{{ $valid->nama }}">
            </div>
        </div>

        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>No.HandPhone:</strong>
                <input type="text" name="hp" class="form-control" placeholder="HP" value="{{ $valid->hp }}">
            </div>
        </div>

        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Email:</strong>
                <input type="text" name="email" class="form-control" placeholder="Email" value="{{ $valid->email }}">
            </div>
        </div>

          <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Alamat:</strong>
                 <textarea class="form-control" name="alamat" rows="5" placeholder="Alamat" >{{ $valid->alamat }}</textarea>
            </div>
        </div>

   @if ( Auth::User()->role == "0")

         <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Jam Booking:</strong>
                <input type="text" name="jambooking" class="form-control" style="background-color: rgb(196, 196, 196)" readonly="disabled" placeholder="Jam Booking"  value="{{ $valid->jambooking }}">
            </div>
        </div>

    

        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Lapangan:</strong>
                <input type="text" name="lapangan" class="form-control" style="background-color: rgb(196, 196, 196)" readonly="disabled" placeholder="Lapangan"  value="{{ $valid->lapangan }}">
            </div>
        </div>

        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Harga:</strong>
                <input type="text" name="harga" class="form-control" style="background-color: rgb(196, 196, 196)" readonly="disabled"  placeholder="Harga"  value="{{ $valid->harga }}">
            </div>
        </div>

        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Credit:</strong>
                <input type="text" name="credit" class="form-control" style="background-color: rgb(196, 196, 196)" readonly="disabled"  placeholder="Credit" value="{{ $valid->credit }}">
            </div>
        </div>

          <!-- <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Status:</strong>
                <input type="text" name="status" class="form-control" style="background-color: rgb(196, 196, 196)" readonly="disabled" placeholder="Status" value="{{ $valid->status }}">
            </div>
        </div> -->

@endif



@if (Auth::User()->role == "admin") 
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Jam Booking:</strong>
                <input type="text" name="jambooking" class="form-control" placeholder="Jam Booking" value="{{ $valid->jambooking }}">
            </div>
        </div>

    

        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Lapangan:</strong>
                <input type="text" name="lapangan" class="form-control"  placeholder="Lapangan"  value="{{ $valid->lapangan }}">
            </div>
        </div>

        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Harga:</strong>
                <input type="text" name="harga" class="form-control" placeholder="Harga" value="{{ $valid->harga }}">
            </div>
        </div>

        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Credit:</strong>
                <input type="text" name="credit" class="form-control"  placeholder="Credit" value="{{ $valid->credit }}">
            </div>
        </div>

          <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Status DP:</strong>
                <input type="text" name="status" class="form-control" readonly="disabled" placeholder="Status" value="{{ $valid->status }}">
            </div>
        </div>
        {{-- Jika Transasi Lunas maka tidak usah tampil untuk edit pelunasannya --}}
                @if ($valid->status == "Transaksi Lunas") 
                     
                <div div class=" ml-3 mb-3">
                            <label for="status" class="form-label">Status Edit:</label>
                           <br>
                            <select class="btn btn-primary" name="status" class="form-control @error('status') is-invalid @enderror" id="status" value="{{ $valid->status }}">
                            @if ($valid->status == "Transaksi Lunas")
                        <option selected value="Transaksi Lunas">{{ $valid->status }}</option>
                             <option value="Belum Lunas">Belum Lunas</option>
                         </select>
                            @endif
                            
                        @error('lapangan')
                            <div class="invalid-feedback">{{ $message }}</div>
                            @enderror    
                </div>      
                @else
       {{-- Jika Belum Lunas maka tampil untuk edit pelunasannya --}}
                    <div div class=" ml-3 mb-3">
                            <label for="status" class="form-label">Status DP:</label>
                           <br>
                            <select class="btn btn-primary" name="status" class="form-control @error('status') is-invalid @enderror" id="status" value="{{ $valid->status }}">
                            <option selected value="Belum Lunas">Belum Lunas</option>
                             <option value="Transaksi Lunas">Transaksi Lunas</option>
                         </select>
                            @error('lapangan')
                            <div class="invalid-feedback">{{ $message }}</div>
                            @enderror
                        @endif
                    @endif
                    </div>

                     
                    

        <div class="col-xs-12 col-sm-12 col-md-12 text-center p-5">
            <button type="submit" class="btn btn-primary m-5">Update</button>
        </div>
    </div>

    </form>
@endsection

resources/views/valid/index.blade.php
@extends('template')

@section('content')

 
    <div class="row mt-5 mb-5">
     <div class="col-lg-12 margin-tb">
         <button type="button" style="font-size: 25px;" class="btn btn-dark">Dana: <span class="badge" style="font-size: 20px;">085123456789</span></button>
         <button type="button" style="font-size: 25px;" class="btn btn-dark">Ovo: <span class="badge" style="font-size: 20px;">01234567890</span></button>
        <br><br>
         
        <h3 class="btn btn-success" style="border-radius: 50px; ">Jam Booking: </h3><br>

@foreach ($valid as $validation)

@if( Auth()->User()->id == $validation->id_valid || $validation->status_booking == "Belum Booking" || Auth::User()->role == "admin" || Auth::User()->role == "0" )

   <a href="#"> <button type="button" style="font-size: 20px; margin-bottom: 10px; border-radius: 50px;" class="btn btn-danger">
     06:00
   </button></a>
   @else
   <button type="button" style="font-size: 20px; margin-bottom: 10px; border-radius: 50px;" id="Btn" class="btn btn-primary" onclick="window.location.href='/booking-jam-6'">
      06:00
  </button>

@endif
    @endforeach

  <button type="button" style="font-size: 20px; margin-bottom: 10px; border-radius: 50px;" id="Btn" class="btn btn-primary" onclick="window.location.href='/booking-jam-6'">
      06:00
  </button>


        <a href="/booking-jam-7" > <button type="button" style="font-size: 20px; margin-bottom: 10px; border-radius: 50px;" class="btn btn-primary">
          07:00
        </button></a>
      <a href="/booking-jam-8"> <button type="button" style="font-size: 20px; margin-bottom: 10px; border-radius: 50px;" class="btn btn-primary">
          08:00
        </button></a>
        <a href="/booking-jam-9"> <button type="button" style="font-size: 20px; margin-bottom: 10px; border-radius: 50px;" class="btn btn-primary">
          09:00
        </button></a>
    
        <a href="/booking-jam-10"> <button type="button" style="font-size: 20px; margin-bottom: 10px; border-radius: 50px;" class="btn btn-primary">
          10:00
        </button></a>
        <a href="/booking-jam-11"> <button type="button" style="font-size: 20px; margin-bottom: 10px; border-radius: 50px;" class="btn btn-primary">
          11:00
        </button></a>
        <a href="/booking-jam-12"> <button type="button" style="font-size: 20px; margin-bottom: 10px; border-radius: 50px;" class="btn btn-primary">
          12:00
        </button></a>
        <a href="/booking-jam-13"> <button type="button" style="font-size: 20px; margin-bottom: 10px; border-radius: 50px;" class="btn btn-primary">
          13:00
        </button></a>
        <a href="/booking-jam-14"> <button type="button" style="font-size: 20px; margin-bottom: 10px; border-radius: 50px;" class="btn btn-primary">
          14:00
        </button></a>
        <a href="/booking-jam-15"> <button type="button" style="font-size: 20px; margin-bottom: 10px; border-radius: 50px;" class="btn btn-primary">
          15:00
        </button></a>
        <a href="/booking-jam-16"> <button type="button" style="font-size: 20px; margin-bottom: 10px; border-radius: 50px;" class="btn btn-primary">
          16:00
        </button></a>
        <a href="/booking-jam-17"> <button type="button" style="font-size: 20px; margin-bottom: 10px; border-radius: 50px;" class="btn btn-primary">
          17:00
        </button></a>
        <a href="/booking-jam-18"> <button type="button" style="font-size: 20px; margin-bottom: 10px; border-radius: 50px;" class="btn btn-primary">
          18:00
        </button></a>
        <a href="/booking-jam-19"> <button type="button" style="font-size: 20px; margin-bottom: 10px; border-radius: 50px;" class="btn btn-primary">
          19:00
        </button></a>
      <a href="/booking-jam-20"> <button type="button" style="font-size: 20px; margin-bottom: 10px; border-radius: 50px;" class="btn btn-primary">
          20:00
        </button></a>
        <a href="/booking-jam-21"> <button type="button" style="font-size: 20px; margin-bottom: 10px; border-radius: 50px;" class="btn btn-primary">
          21:00
        </button></a>
        <a href="/booking-jam-22"> <button type="button" style="font-size: 20px; margin-bottom: 10px; border-radius: 50px;" class="btn btn-primary">
          22:00
        </button></a>
        <a href="/booking-jam-23"> <button type="button" style="font-size: 20px; margin-bottom: 10px; border-radius: 50px;" class="btn btn-primary">
          23:00
        </button></a>

         <br><br>
 <b><p style="font-style: italic; text-decoration: underline;">Segera Mengirim Bukti DP Dan Konfirmasi Admin !!</p></b>

         <div class="float-right">
                <!-- <a class="btn btn-success" href="{{ route('valid.create') }}">Booking Futsal</a> -->
            </div>
        </div>
    </div>

    @if ($message = Session::get('succes'))
    <div class="alert alert-success">
        <p>{{ $message }}</p>
    </div>
    @endif

   <table class="table">
  <thead class="table-dark" >
        <tr>
            <th class="text-center">No</th>
            <th class="text-center">Status_Booking</th>
            {{-- <th width="50px" class="text-center">Role</th> --}}
          <!-- <th width="50px"class="text-center">Id_Valid</th>  -->
            <th class="text-center">Nama</th>
            <th class="text-center">No.HandPhone</th>
            <th  class="text-center">Email</th>
            <th  class="text-center">Alamat</th>
            <th  class="text-center">Jam Booking</th>
            <th class="text-center">Lapangan</th>
            <th class="text-center">Harga DP</th>
            <th  class="text-center">Credit</th>
            <th  class="text-center">Status Booking</th>
            <th  class="text-center">Tanggal</th>
            <th  class="text-center">Action</th>
        </tr>
  </thead>
        @foreach ($valid as $validation)
         @if (Auth()->User()->id == $validation->id_valid || Auth()->User()->role == 'admin')
 <tbody class="table-primary" >            
        <tr>
            <td class="text-center">{{ ++$i }}</td>
           
            <td><span class="badge badge-success">{{ $validation->status_booking }}</span></td>
            {{-- <td>{{ $validation->role }}</td> --}}
            <!-- <td>{{ $validation->id_valid }}</td> -->
            <td>{{ $validation->nama }}</td>
            <td>{{ $validation->hp }}</td>
            <td>{{ $validation->email }}</td>
            <td>{{ $validation->alamat }}</td>
            @if ($validation->status_booking == "Sudah Booking")
            <td>{{ $validation->jambooking }}</td>
            @else  
            <td>{{ $validation->jambooking }}</td>
            @endif   
            <td>{{ $validation->lapangan }}</td>
            <td readonly="disabled">Rp.{{ $validation->harga }}</td>
            <td>{{ $validation->credit }}</td>
                @if ($validation->status == "Transaksi Lunas")
            <td><span class="badge badge-success">{{ $validation->status }}</span></td>
            @else
            <td><span class="badge badge-danger">{{ $validation->status }}</span></td>

            @endif
            <td>{{ $validation->created_at }}</td>
            <td class="text-center">
                <form action="{{ route('valid.destroy',$validation->id) }}" method="POST">
                 <a href="{{ route('valid.show',$validation->id) }}"><button type="button" class="btn btn-warning btn-sm">
                    <i class="fas fa-eye"></i>
                </button></a>

                <a  href="{{ route('valid.edit',$validation->id) }}"><button type="button" class="btn btn-info btn-sm">
                    <i class="fas fa-edit"></i>
                </button></a>

                @csrf
                @method('DELETE')
            <br>
                <button type="submit" class="btn btn-danger btn-sm" onclick="return confirm('Apakah Anda yakin ingin menghapus data ini?')">
                    <i class="fas fa-trash"></i>
                </button>

                </form>
            </td>
        </tr>
 </tbody>
        @endif

        @endforeach
    </table>

    <script>
function myFunction() {
    var x = document.getElementById("Btn");
    x.disabled = true;
}
</script>
@endsection